# example workflow for Polaris scans using the Black Duck Security Scan Action
# https://github.com/marketplace/actions/black-duck-security-scan
name: polaris-signal
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  polaris:
    runs-on: linux64-vpn
    steps:
    - name: Checkout Source
      uses: actions/checkout@v6
    - name: Setup Java JDK
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: temurin
        cache: maven
    - name: Polaris Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      env:
        BRIDGE_SIGNAL_LLM_URL: ${{ vars.LLM_URL }}
        BRIDGE_SIGNAL_LLM_KEY: ${{ secrets.LLM_KEY }}
      with:
        polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESSTOKEN }}
        polaris_assessment_types: AI
        polaris_application_name: chuckaude-hello-java
        polaris_prComment_enabled: false
        polaris_reports_sarif_create: true
        polaris_upload_sarif_report: true
        coverity_build_command: mvn -B -DskipTests package
        coverity_clean_command: mvn -B clean
        github_token: ${{ secrets.GITHUB_TOKEN }}
        include_diagnostics: true
