name: polaris-signal-pr
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  polaris:
    runs-on: sdc-sal-apps316
    steps:
    - name: Checkout Source
      uses: actions/checkout@v6
      with:
        fetch-depth: 2
    - name: Setup Java JDK
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: temurin
        cache: maven
    - name: Polaris Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      uses: blackduck-inc/black-duck-security-scan@v2
      env:
        BRIDGE_SIGNAL_LLM_URL: ${{ vars.LLM_URL }}
        BRIDGE_SIGNAL_LLM_KEY: ${{ secrets.LLM_KEY }}
      with:
        polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESSTOKEN }}
        polaris_assessment_types: AI
        polaris_application_name: chuckaude-hello-java
        include_diagnostics: true
    - name: Polaris PR Scan
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        CHANGESET=$(git diff --name-only -r HEAD^1 HEAD | xargs)
        $HOME/.blackduck/bridge/tools/signal/*/signal --llm-uri ${{ vars.LLM_URL }} --llm-key ${{ secrets.LLM_KEY }} $CHANGESET
